"""
OED active-artifact resolver.

Given an OED run directory, this module returns a structured descriptor of
the winning code modification — independent of which category it was. The
post-OED stages (experiment_designer, foam_run, input_writer, reviewer) need
to know:

  * what kind of modification the OED produced (runtime source term?
    derived turbulence/transport class? dictionary edit?),
  * where the source files live (so they can be COPIED, not regenerated),
  * what coefficient names the variant exposes (so per-case sweeps tweak
    the right keys, not LLM-invented synonyms).

This is generic across CFD topics (turbulence, viscosity, BC, source term,
function object, scheme, …) — the resolver only inspects on-disk artifacts.

CLI:
    python scripts/oed_artifact.py --run-dir <run_dir>

Output: JSON with the artifact descriptor printed to stdout.

Programmatic use:
    from oed_artifact import resolve_oed_artifact
    art = resolve_oed_artifact(Path(run_dir))
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional


def _read_json(p: Path, default: Any) -> Any:
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return default


def _walk_history_pick_best(history: List[Dict[str, Any]],
                            baseline_value: Optional[float],
                            baseline_direction: str) -> Optional[Dict[str, Any]]:
    """Walk history newest→oldest and pick the entry with the best score.

    Generic across QoIs: respects baseline_direction (min vs max) when
    determining "better". Falls back to last PROCEED entry if no scored
    entries exist.
    """
    direction = (baseline_direction or "min").strip().lower()
    if direction not in ("min", "max"):
        direction = "min"

    scored: List[Dict[str, Any]] = []
    for h in history:
        if not isinstance(h, dict):
            continue
        s = h.get("score")
        v = None
        if isinstance(s, dict):
            try:
                v = float(s.get("value"))
            except Exception:
                v = None
        if v is None:
            continue
        scored.append({**h, "_score_value": v})

    if not scored:
        # Fall back to last PROCEED (or last entry that produced a case_dir).
        for h in reversed(history):
            if isinstance(h, dict) and h.get("status") == "PROCEED" and h.get("case_dir"):
                return h
        return None

    if direction == "max":
        return max(scored, key=lambda x: x["_score_value"])
    return min(scored, key=lambda x: x["_score_value"])


def _find_iter_dir_for(history_entry: Dict[str, Any], oed_dir: Path) -> Optional[Path]:
    """Locate the iter_NNN_* dir on disk that produced this history entry."""
    iteration = history_entry.get("iteration")
    if iteration is None:
        return None
    pat = f"iter_{int(iteration):03d}_*"
    matches = list(oed_dir.glob(pat))
    if matches:
        return matches[0]
    return None


def _resolve_runtime_source_artifact(iter_dir: Path) -> Optional[Dict[str, Any]]:
    """If this iter is a runtime_source/runtime_field/runtime_bc, return a
    descriptor pointing at the actual edited dictionary (typically
    `constant/fvModels` for runtime_source, but we scan all candidates)."""
    # Where the runtime applier put its output
    candidates = [
        iter_dir / "canonical_base_case",
        iter_dir / "retry_01" / "canonical_base_case",
        iter_dir / "retry_02" / "canonical_base_case",
        iter_dir / "retry_03" / "canonical_base_case",
        iter_dir / "retry_04" / "canonical_base_case",
        iter_dir / "retry_05" / "canonical_base_case",
    ]
    base_case: Optional[Path] = None
    for c in candidates:
        if (c / "constant").is_dir() and (c / "system").is_dir():
            base_case = c
            break
    if base_case is None:
        return None

    # Identify which dictionary the runtime mod edited.
    edited: List[Path] = []
    for rel in ("constant/fvModels", "constant/fvOptions", "constant/fvConstraints",
                "system/controlDict"):
        p = base_case / rel
        if p.is_file():
            text = p.read_text(encoding="utf-8", errors="replace")
            if "(generated by code_mod_runtime)" in text or "type            coded" in text:
                edited.append(p)

    # 0/<field> patches for coded BCs
    zero_dir = base_case / "0"
    if zero_dir.is_dir():
        for f in zero_dir.iterdir():
            if not f.is_file():
                continue
            try:
                text = f.read_text(encoding="utf-8", errors="replace")[:8000]
            except Exception:
                continue
            if "type            codedFixedValue" in text or "codedMixed" in text:
                edited.append(f)

    if not edited:
        return None

    # Extract coefficient names from the first edited file (best-effort).
    # Generic: look for `Cname  value;` lines that appear before the
    # codeInclude/codeAddSup blocks (i.e. they're scalar entries, not C++).
    coeff_names: List[str] = []
    fvm_text = ""
    try:
        fvm_text = edited[0].read_text(encoding="utf-8", errors="replace")
        # take everything up to the first codeInclude or codeAddSup
        head = fvm_text
        for marker in ("codeInclude", "codeAddSup", "codeAddRhoSup",
                       "codeAddAlphaRhoSup", "code "):
            idx = head.find(marker)
            if idx > 0:
                head = head[:idx]
        # match `name    value;` where value is a number/scalar literal
        for m in re.finditer(r"^\s+([A-Za-z_][A-Za-z0-9_]*)\s+(-?\d+\.?\d*(?:e[+-]?\d+)?)\s*;",
                              head, flags=re.MULTILINE):
            name = m.group(1)
            if name.lower() in {"version", "format", "class", "location", "object",
                                 "selectionmode", "field", "type", "name"}:
                continue
            if name not in coeff_names:
                coeff_names.append(name)
    except Exception:
        coeff_names = []

    return {
        "category": "runtime_source",
        "base_case_dir": str(base_case),
        "edited_files": [str(p) for p in edited],
        "primary_dictionary": str(edited[0]),
        "coefficient_names": coeff_names,
        "snippet_text": fvm_text[:20000],
    }


def _resolve_class_derivation_artifact(iter_dir: Path) -> Optional[Dict[str, Any]]:
    """If this iter is a class_derivation, return descriptor pointing at the
    customModels source dir AND the compiled .so (if found)."""
    # Look for any customModels dir under iter_dir.
    custom_dirs = list(iter_dir.rglob("customModels"))
    custom_models_dir: Optional[Path] = None
    for d in custom_dirs:
        if d.is_dir() and any((d / sub).is_dir() for sub in os.listdir(d) if (d / sub).is_dir()):
            custom_models_dir = d
            break
    if custom_models_dir is None:
        return None

    # The actual class subdir(s).
    class_dirs = [d for d in custom_models_dir.iterdir() if d.is_dir() and (d / "Make").is_dir()]
    if not class_dirs:
        return None
    class_dir = class_dirs[0]
    class_name = class_dir.name

    # Locate the .so. Search case-local platforms/ AND $FOAM_USER_LIBBIN.
    so_paths: List[Path] = []
    so_paths.extend(custom_models_dir.rglob(f"lib{class_name}*.so"))
    libbin = os.environ.get("FOAM_USER_LIBBIN", "").strip()
    if not libbin:
        home = Path(os.environ.get("HOME", str(Path.home())))
        for ulb in home.glob("OpenFOAM/*-*/platforms/*/lib"):
            libbin = str(ulb)
            break
    if libbin and Path(libbin).is_dir():
        so_paths.extend(Path(libbin).glob(f"lib{class_name}*.so"))
    so_paths = [p for p in so_paths if p.is_file()]

    # Find the case dir that USED this lib (has 0/, constant/, system/).
    case_dir: Optional[Path] = None
    for d in iter_dir.rglob("system"):
        parent = d.parent
        if (parent / "constant").is_dir() and (parent / "0").is_dir() and parent != custom_models_dir.parent:
            case_dir = parent
            break

    return {
        "category": "class_derivation",
        "class_name": class_name,
        "lib_name": f"lib{class_name}.so",
        "customModels_dir": str(custom_models_dir),
        "class_source_dir": str(class_dir),
        "compiled_so_paths": [str(p) for p in so_paths],
        "base_case_dir": str(case_dir) if case_dir else "",
    }


def _resolve_dict_only_artifact(iter_dir: Path) -> Optional[Dict[str, Any]]:
    """If this iter is dict_only, return the patched dictionaries."""
    base_case = None
    for c in (iter_dir / "canonical_base_case", iter_dir):
        if (c / "constant").is_dir() and (c / "system").is_dir():
            base_case = c
            break
    if base_case is None:
        return None
    return {
        "category": "dict_only",
        "base_case_dir": str(base_case),
    }


def _build_descriptor_from_case_dir(
    case_dir: Path,
    history_entry: Dict[str, Any],
    *,
    baseline_value: Optional[float],
    baseline_direction: str,
    run_dir: Path,
    baseline_metrics: Dict[str, Any],
) -> Dict[str, Any]:
    """Build an artifact descriptor by inspecting an OpenFOAM case dir
    that already ran successfully. Generic across categories — detects the
    edited dictionaries on the case automatically (coded fvModels, coded
    BCs, customModels, dict-only patches)."""

    edited_files: List[Path] = []
    coeff_names: List[str] = []
    snippet_text = ""
    category = "unknown"
    custom_models_dir: Optional[Path] = None
    class_name = ""
    so_paths: List[Path] = []

    # Coded entries in constant/fvModels, fvOptions, fvConstraints
    for rel in ("constant/fvModels", "constant/fvOptions", "constant/fvConstraints"):
        p = case_dir / rel
        if p.is_file():
            try:
                t = p.read_text(encoding="utf-8", errors="replace")
                if "(generated by code_mod_runtime)" in t or "type            coded" in t:
                    edited_files.append(p)
                    if not snippet_text:
                        snippet_text = t
                    if category == "unknown":
                        category = "runtime_source"
            except Exception:
                pass

    # Coded BCs in 0/<field>
    zero_dir = case_dir / "0"
    if zero_dir.is_dir():
        for f in zero_dir.iterdir():
            if not f.is_file():
                continue
            try:
                t = f.read_text(encoding="utf-8", errors="replace")[:8000]
            except Exception:
                continue
            if "type            codedFixedValue" in t or "codedMixed" in t:
                edited_files.append(f)
                if category == "unknown":
                    category = "runtime_bc"

    # customModels source + .so for class_derivation
    custom_dirs = list(case_dir.rglob("customModels"))
    for d in custom_dirs:
        if d.is_dir():
            class_dirs = [x for x in d.iterdir() if x.is_dir() and (x / "Make").is_dir()]
            if class_dirs:
                custom_models_dir = d
                class_name = class_dirs[0].name
                category = "class_derivation"
                # find .so
                so_paths.extend(d.rglob(f"lib{class_name}*.so"))
                libbin = os.environ.get("FOAM_USER_LIBBIN", "").strip()
                if not libbin:
                    home = Path(os.environ.get("HOME", str(Path.home())))
                    for ulb in home.glob("OpenFOAM/*-*/platforms/*/lib"):
                        libbin = str(ulb)
                        break
                if libbin and Path(libbin).is_dir():
                    so_paths.extend(Path(libbin).glob(f"lib{class_name}*.so"))
                so_paths = [p for p in so_paths if p.is_file()]
                break

    # For class_derivation: extract coefficient names from the activation
    # dict's <Class>Coeffs sub-block. This is where the actual scalar
    # coefficients live for compiled OpenFOAM models — NOT in fvModels.
    # Generic across activation dicts (turbulence: momentumTransport;
    # viscosity: transportProperties; thermal: thermo properties dict).
    parent_class_name = ""
    activation_dict_path = ""
    coefficient_block_name = ""
    novel_coeffs: List[str] = []
    if category == "class_derivation" and class_name:
        coefficient_block_name = f"{class_name}Coeffs"
        # Try common activation dictionaries
        for rel in ("constant/momentumTransport",
                    "constant/turbulenceProperties",
                    "constant/transportProperties",
                    "constant/thermophysicalProperties"):
            ap = case_dir / rel
            if ap.is_file():
                try:
                    txt = ap.read_text(encoding="utf-8", errors="replace")
                except Exception:
                    continue
                if coefficient_block_name in txt:
                    activation_dict_path = str(ap)
                    snippet_text = txt
                    # Extract coefficient names from the sub-block.
                    head = txt
                    m_block = re.search(rf"\b{re.escape(coefficient_block_name)}\s*\{{", head)
                    if m_block:
                        start = m_block.end()
                        depth = 1
                        i = start
                        while i < len(head) and depth > 0:
                            c = head[i]
                            if c == "{":
                                depth += 1
                            elif c == "}":
                                depth -= 1
                                if depth == 0:
                                    break
                            i += 1
                        block = head[start:i]
                        for mm in re.finditer(
                            r"^\s+([A-Za-z_][A-Za-z0-9_]*)\s+(-?\d+\.?\d*(?:e[+-]?\d+)?)\s*;",
                            block, flags=re.MULTILINE):
                            name = mm.group(1)
                            if name.lower() in {
                                "version", "format", "class", "location", "object",
                                "selectionmode", "field", "type", "name",
                            }:
                                continue
                            if name not in coeff_names:
                                coeff_names.append(name)
                    break

        # Parse the .H file: extract parent class name AND novel coefficients
        # (the new dimensionedScalar members declared by the subclass — these
        # are the meaningful sweep axes, not the inherited standard constants
        # like Cb1, Cb2, kappa). Generic across any OpenFOAM subclass that
        # introduces new coefficients via `dimensionedScalar X_;` member
        # declarations.
        if custom_models_dir is not None:
            for class_dir in custom_models_dir.iterdir():
                if not (class_dir.is_dir() and class_dir.name == class_name):
                    continue
                h_path = class_dir / f"{class_name}.H"
                if not h_path.is_file():
                    continue
                try:
                    h_txt = h_path.read_text(encoding="utf-8", errors="replace")
                except Exception:
                    break
                pm = re.search(r"public\s+([A-Za-z_][A-Za-z0-9_]*)\s*<", h_txt)
                if pm:
                    parent_class_name = pm.group(1)
                # Each `dimensionedScalar Foo_;` declaration in the new class
                # body is a novel coefficient. Strip the trailing underscore
                # to match the dict-form name (Foo).
                for nm in re.finditer(
                    r"\bdimensionedScalar\s+([A-Za-z_][A-Za-z0-9_]*)_\s*;",
                    h_txt,
                ):
                    nname = nm.group(1)
                    if nname not in novel_coeffs and nname in coeff_names:
                        novel_coeffs.append(nname)
                break

    # Extract coefficient names from coded snippet (best-effort).
    if snippet_text:
        head = snippet_text
        for marker in ("codeInclude", "codeAddSup", "codeAddRhoSup",
                       "codeAddAlphaRhoSup", "code "):
            idx = head.find(marker)
            if idx > 0:
                head = head[:idx]
        for m in re.finditer(r"^\s+([A-Za-z_][A-Za-z0-9_]*)\s+(-?\d+\.?\d*(?:e[+-]?\d+)?)\s*;",
                              head, flags=re.MULTILINE):
            name = m.group(1)
            if name.lower() in {"version", "format", "class", "location", "object",
                                 "selectionmode", "field", "type", "name"}:
                continue
            if name not in coeff_names:
                coeff_names.append(name)

    if category == "unknown":
        # Pure dict_only or unrecognized — still usable as a base case.
        category = "dict_only"

    # For class_derivation, primary_dictionary points at the activation
    # dict (where coefficients are patchable). For runtime_source it points
    # at the edited file (e.g. constant/fvModels).
    primary = ""
    if category == "class_derivation" and activation_dict_path:
        primary = activation_dict_path
    elif edited_files:
        primary = str(edited_files[0])

    return {
        "status": "ok",
        "category": category,
        "base_case_dir": str(case_dir),
        "edited_files": [str(p) for p in edited_files],
        "primary_dictionary": primary,
        "coefficient_names": coeff_names,
        "novel_coefficient_names": novel_coeffs if category == "class_derivation" else [],
        "coefficient_block_name": coefficient_block_name,
        "parent_class_name": parent_class_name,
        "snippet_text": snippet_text[:20000],
        "customModels_dir": str(custom_models_dir) if custom_models_dir else "",
        "class_name": class_name,
        "lib_name": f"lib{class_name}.so" if class_name else "",
        "compiled_so_paths": [str(p) for p in so_paths],
        "source_iteration": history_entry.get("iteration"),
        "best_iteration": history_entry.get("iteration"),
        "best_score": history_entry.get("score"),
        "model_description": (history_entry.get("model_description") or "")[:600],
        "formula": (history_entry.get("formula") or "")[:600],
        "baseline_score": baseline_value,
        "baseline_direction": baseline_direction,
        "topic": baseline_metrics.get("topic", "") if isinstance(baseline_metrics, dict) else "",
        "run_dir": str(run_dir),
    }


def _resolve_regular_code_mod_artifact(run_dir: Path,
                                       baseline_metrics: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Detect a *regular* (user-prescribed, non-OED) code_mod artifact under
    `run_dir`. Layout written by the regular code_mod pipeline:

      <run_dir>/canonical_base_case/        (the working case)
      <run_dir>/code_mod_apply_result.json  (renderer output, present for
                                              runtime_source/_bc/_field/dict_only)
      <run_dir>/code_mod_build_result.json  (compile result, present for
                                              class_derivation)
      <run_dir>/code_mod_payload.json       (the original user spec)

    Returns a descriptor in the same shape as resolve_oed_artifact. Generic
    across modification kinds.
    """
    base = run_dir / "canonical_base_case"
    apply_p = run_dir / "code_mod_apply_result.json"
    build_p = run_dir / "code_mod_build_result.json"
    payload_p = run_dir / "code_mod_payload.json"
    if not base.is_dir():
        return None
    # Need at least apply or build evidence to consider this a code_mod run.
    if not apply_p.is_file() and not build_p.is_file():
        return None

    apply_d = _read_json(apply_p, {}) if apply_p.is_file() else {}
    build_d = _read_json(build_p, {}) if build_p.is_file() else {}
    payload_d = _read_json(payload_p, {}) if payload_p.is_file() else {}

    # Synthesize a "history entry" for descriptor builder
    pseudo_entry: Dict[str, Any] = {
        "iteration": 0,
        "modification_category": (
            apply_d.get("category")
            or build_d.get("category")
            or payload_d.get("modification_category")
            or ""
        ),
        "compiled_model_name": (
            build_d.get("class_name")
            or apply_d.get("class_name")
            or payload_d.get("variant_name", "")
        ),
        "compiled_so": build_d.get("compiled_so", "") or "",
        "compiled_case_dir": str(base),
        "case_dir": str(base),
        "model_description": (
            payload_d.get("model_description")
            or payload_d.get("formula_or_modification", "")[:300]
            or "regular code_mod variant"
        ),
        "formula": payload_d.get("formula_or_modification", "")[:600],
        "score": None,
    }
    bs = baseline_metrics.get("primary_score") if isinstance(baseline_metrics, dict) else None
    bs_v = bs.get("value") if isinstance(bs, dict) else None
    bs_d = bs.get("direction", "min") if isinstance(bs, dict) else "min"
    descriptor = _build_descriptor_from_case_dir(
        base, pseudo_entry,
        baseline_value=bs_v, baseline_direction=bs_d,
        run_dir=run_dir, baseline_metrics=baseline_metrics,
    )
    descriptor["provenance"] = "regular_code_mod"
    return descriptor


def resolve_oed_artifact(run_dir: Path) -> Dict[str, Any]:
    """Top-level resolver. Returns a descriptor of the run's active code-
    modification artifact. Generic across:
      - OED open_ended_discovery winners
      - regular (user-prescribed) code_mod path

    Always returns a dict (never None). When no usable artifact is found,
    the returned dict has `status: "no_artifact"` so callers can
    short-circuit cleanly.
    """
    run_dir = Path(run_dir).resolve()
    oed_dir = run_dir / "open_ended_discovery"
    baseline_metrics = _read_json(run_dir / "baseline_metrics.json", {})

    # First try the regular code_mod path. If the run was a one-shot
    # user-prescribed code_mod (no OED), this is the canonical artifact.
    regular = _resolve_regular_code_mod_artifact(run_dir, baseline_metrics)
    if regular is not None and not oed_dir.is_dir():
        return regular

    if not oed_dir.is_dir():
        return {"status": "no_artifact", "reason": "no open_ended_discovery dir and no regular code_mod artifact"}

    summary = _read_json(oed_dir / "summary.json", {})
    history = _read_json(oed_dir / "history.json", [])
    if not isinstance(history, list) or not history:
        # OED dir exists but is empty — fall back to regular code_mod artifact if any.
        if regular is not None:
            return regular
        return {"status": "no_artifact", "reason": "history empty and no regular code_mod artifact"}

    bs = baseline_metrics.get("primary_score") if isinstance(baseline_metrics, dict) else None
    bs_v = bs.get("value") if isinstance(bs, dict) else None
    bs_d = bs.get("direction", "min") if isinstance(bs, dict) else "min"

    # Pick the iter to use as the artifact source. Order:
    #   1. The COMPILE-PRODUCING iter that the best PROCEED iter inherits from.
    #      (e.g. iter 29 is an experiment-mode parameter sweep on iter 19's
    #      compiled snippet — the artifact lives in iter 19, not 29.)
    #   2. The best-scored iter directly.
    best = _walk_history_pick_best(history, bs_v, bs_d)
    if best is None:
        return {"status": "no_artifact", "reason": "no scored iter"}

    # Direct path: best iter's `case_dir` IS the working OpenFOAM case (it
    # already ran simpleFoam to End with the winning coefficients applied).
    # Use it as-is when present and valid.
    case_dir_str = (best.get("case_dir") or "").strip()
    if case_dir_str and Path(case_dir_str).is_dir() \
            and (Path(case_dir_str) / "constant").is_dir() \
            and (Path(case_dir_str) / "system").is_dir():
        case_path = Path(case_dir_str)
        return _build_descriptor_from_case_dir(
            case_path,
            best,
            baseline_value=bs_v,
            baseline_direction=bs_d,
            run_dir=run_dir,
            baseline_metrics=baseline_metrics,
        )

    # Climb to the underlying compile-producing iter when best is an
    # experiment-mode reuse and best.case_dir is missing.
    source_iter = best
    if best.get("action_type") == "experiment":
        reuse = (best.get("compiled_model_name") or "").strip()
        if reuse:
            for h in history:
                if (
                    isinstance(h, dict)
                    and h.get("action_type") == "code_mod"
                    and (h.get("compiled_model_name") or "").strip() == reuse
                ):
                    source_iter = h
                    break

    iter_dir = _find_iter_dir_for(source_iter, oed_dir)
    if iter_dir is None:
        return {"status": "no_artifact", "reason": "iter dir not found on disk"}

    cat = (source_iter.get("modification_category") or "").strip().lower()

    descriptor: Optional[Dict[str, Any]] = None
    if cat in {"runtime_source", "runtime_bc", "runtime_field"}:
        descriptor = _resolve_runtime_source_artifact(iter_dir)
    elif cat == "class_derivation":
        descriptor = _resolve_class_derivation_artifact(iter_dir)
    elif cat == "dict_only":
        descriptor = _resolve_dict_only_artifact(iter_dir)

    # If category-specific resolution failed, try them in order.
    if descriptor is None:
        for fn in (_resolve_runtime_source_artifact,
                   _resolve_class_derivation_artifact,
                   _resolve_dict_only_artifact):
            descriptor = fn(iter_dir)
            if descriptor is not None:
                break

    if descriptor is None:
        return {"status": "no_artifact", "reason": f"no artifact resolvable in {iter_dir}"}

    # Augment with provenance
    descriptor["status"] = "ok"
    descriptor["source_iteration"] = source_iter.get("iteration")
    descriptor["source_iter_dir"] = str(iter_dir)
    descriptor["best_iteration"] = best.get("iteration")
    descriptor["best_score"] = best.get("score")
    descriptor["model_description"] = (
        source_iter.get("compiled_model_description")
        or source_iter.get("model_description")
        or ""
    )[:600]
    descriptor["baseline_score"] = bs_v
    descriptor["baseline_direction"] = bs_d
    descriptor["topic"] = baseline_metrics.get("topic", "") if isinstance(baseline_metrics, dict) else ""
    descriptor["run_dir"] = str(run_dir)
    return descriptor


def main() -> None:
    ap = argparse.ArgumentParser(description="Resolve OED winning artifact")
    ap.add_argument("--run-dir", required=True, type=Path)
    ap.add_argument("--output", type=Path, default=None,
                    help="Optional: write JSON descriptor to this path")
    args = ap.parse_args()
    descriptor = resolve_oed_artifact(args.run_dir)
    s = json.dumps(descriptor, indent=2, default=str)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(s, encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(s)


if __name__ == "__main__":
    main()
